name: ServerStatus
main: xyz.skylar11d.minecraftp.serverstatus.Main
version: %project_version%
api-version: 1.20
depend: [packetevents]
softdepend: [ProtocolLib, PlaceHolderAPI]
description: A simple plugin to alter the server's status at multiplayer menu
load: POSTWORLD
author: Skylar11D
website: Skylar11D.xyz